AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false