inherit_gem:
  theforeman-rubocop:
    - default.yml

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 190

Metrics/ParameterLists:
  Max: 6

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/foreman_vault/engine.rb
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - Rakefile

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Naming/FileName:
  Exclude:
    - db/seeds.d/103-provisioning_templates.rb
