AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'
    - 'node_modules/**/*'
    - 'locale/*'
    - 'vendor/**/*'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

Rails:
  Enabled: true

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/foreman_vault/*.rake'
    - 'lib/tasks/*.rake'

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 190

Metrics/ParameterLists:
  Max: 6

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/foreman_vault/engine.rb
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Naming/FileName:
  Exclude:
    - db/seeds.d/103-provisioning_templates.rb

Layout/BlockAlignment:
  Exclude:
    - config/routes.rb
    - db/seeds.d/*.rb
    - test/factories/*.rb

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'foreman_vault.gemspec'
